### ISSUE TITLE
Combined aggregation table includes rows from the future

### ISSUE THREAD

**Issue by mbauman** [dssg/collate#47]
It'd make it a bit easier to prevent temporal leakage if this limited the join to ensure that no rows from the future make it through (even if they're all null).

**Comment by potash** [comment]
Good point. Assigned myself to this.

**Comment by potash** [comment]
On second thought this was actually intentional. Maybe it shouldn't be the default but the idea is that the join should include "all" the entity-date pairs-- including those that don't exist in this particular `from_obj`.

The best way to do that is to provide an explicit `join_table` to `Aggregation.get_create()` but this just takes the cross product of entities in the from_obj with dates. I guess that's not a good default behavior. Maybe a more sensible default is just no join table (i.e. if an entity is not in the `from_obj` it wont be in the aggregation) and then people can specify a join table if they want that. What do you think?

**Comment by mbauman** [comment]
I'm curious — when would you find including entities from the future useful?  It seems dangerous and problematic to me.  Do we ever want to do this?

**Comment by potash** [comment]
The `join_table` feature here is not to include an entity from the future but to include an entity that did not have an entry in the feature data that is being aggregated over.

For example if you're aggregating cases of lead poisoning by address and year and there were no kids tested in a given year. The idea was for this table to include a row for the all (address, date) pairs. I think my original intention was to do imputation here.

Now I definitely think the default should be to not do this but still support the `join_table` arg.

**Comment by mbauman** [comment]
Ah, ok, that makes more sense to me now.  I suppose this would result from using a more complicated `from_obj`?  We could still use a join table by default if we were more careful about which entities it included — but simply sticking a where clause on it isn't sufficient since it has an interaction with the values of the date column.  It'd take more work to construct it.
